---
- name: Fail when service manager is not supported.
  ansible.builtin.fail:
    msg: "Currently only systems that are managed by systemd are supported"
  when: ansible_service_mgr != 'systemd'

- name: Create maven-nodejs-proxy group.
  ansible.builtin.group:
    name: "{{ maven_nodejs_proxy_group }}"
    state: present

- name: Create maven-nodejs-proxy user.
  ansible.builtin.user:
    name: "{{ maven_nodejs_proxy_user }}"
    group: "{{ maven_nodejs_proxy_group }}"
    append: true
    system: true
    state: present

- name: Create maven-nodejs-proxy home folder.
  ansible.builtin.file:
    path: "{{ maven_nodejs_proxy_home }}"
    state: directory
    owner: "{{ maven_nodejs_proxy_user }}"
    group: "{{ maven_nodejs_proxy_group }}"
    mode: "0755"

- name: Create maven-nodejs-proxy log folder.
  ansible.builtin.file:
    path: "{{ maven_nodejs_proxy_log_dir }}"
    state: directory
    owner: "{{ maven_nodejs_proxy_user }}"
    group: "{{ maven_nodejs_proxy_group }}"
    mode: "0755"

- name: Check if maven-nodejs-proxy is already there
  ansible.builtin.stat:
    path: "{{ maven_nodejs_proxy_binary_path }}"
  register: maven_nodejs_proxy_binary_path_result

- name: Build and install maven-nodejs-proxy
  when: maven_nodejs_proxy_force_compile or not maven_nodejs_proxy_binary_path_result.stat.exists
  block:
    - name: Create maven-nodejs-proxy tmp folder.
      ansible.builtin.file:
        path: "{{ maven_nodejs_proxy_tmp }}"
        state: directory
        mode: "0755"

    - name: Clone maven-nodejs-proxy in given version
      ansible.builtin.git:
        repo: "{{ maven_nodejs_proxy_repo }}"
        dest: "{{ maven_nodejs_proxy_tmp }}"
        version: "{{ maven_nodejs_proxy_version | default(omit) }}"
        force: true
        accept_hostkey: true

    - name: Build Maven command line.
      ansible.builtin.set_fact:
        _mvn_cmdline: "{{ maven_nodejs_proxy_maven_cmd }} {{ maven_nodejs_proxy_maven_opts }} clean install -DskipTests"

    - name: Add custom Maven settings.
      ansible.builtin.set_fact:
        _mvn_cmdline: "{{ _mvn_cmdline }} --settings={{ maven_nodejs_proxy_maven_settings }}"
      when: maven_nodejs_proxy_maven_settings is defined

    - name: Compile maven-nodejs-proxy with Maven.
      ansible.builtin.command: "{{ _mvn_cmdline }}"
      args:
        chdir: "{{ maven_nodejs_proxy_tmp }}"
      changed_when: true

    - name: Copy compiled artifact to maven-nodejs-proxy home
      ansible.builtin.copy:
        remote_src: true
        src: "{{ maven_nodejs_proxy_tmp_binary_path }}"
        dest: "{{ maven_nodejs_proxy_binary_path }}"
        owner: "{{ maven_nodejs_proxy_user }}"
        group: "{{ maven_nodejs_proxy_group }}"
        mode: "0644"
      notify:
        - Maven_nodejs_proxy restart

- name: Create config.yml and transfer to remote machine
  ansible.builtin.template:
    src: "templates/config.yml.j2"
    dest: "{{ maven_nodejs_proxy_config_path }}"
    owner: "{{ maven_nodejs_proxy_user }}"
    group: "{{ maven_nodejs_proxy_group }}"
    mode: "0644"
  register: maven_nodejs_proxy_config
  notify:
    - Maven_nodejs_proxy restart

- name: Setup maven-nodejs-proxy systemd unit.
  ansible.builtin.include_tasks: systemd.yml
  when: ansible_service_mgr == 'systemd'
